/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author t.xiong
 */
public class MainView extends javax.swing.JFrame {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);
    
    public void addPropertyChangeListener(PropertyChangeListener listener)
    {
        listeners.addPropertyChangeListener(listener);
    }
    
    public String message(String message){
        return message;
    }
    
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }
    
    public void setTableModel (AbstractTableModel tableModel){
        this.usersList.setModel (tableModel);
        this.usersList.removeColumn(this.usersList.getColumn("Id_utilisateur"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenDialogAjoutUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JTable();
        btnOpenDialogModifUser = new javax.swing.JButton();
        btnOpenDialogSuppUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOpenDialogAjoutUser.setText("Ajout");
        btnOpenDialogAjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDialogAjoutUserActionPerformed(evt);
            }
        });

        usersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usersList);

        btnOpenDialogModifUser.setText("Modification");
        btnOpenDialogModifUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDialogModifUserActionPerformed(evt);
            }
        });

        btnOpenDialogSuppUser.setText("Supprimer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnOpenDialogAjoutUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnOpenDialogModifUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnOpenDialogSuppUser)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnOpenDialogAjoutUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenDialogModifUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpenDialogSuppUser)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenDialogAjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDialogAjoutUserActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("btnClick", null, null);
    }//GEN-LAST:event_btnOpenDialogAjoutUserActionPerformed

    private void btnOpenDialogModifUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDialogModifUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenDialogModifUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenDialogAjoutUser;
    private javax.swing.JButton btnOpenDialogModifUser;
    private javax.swing.JButton btnOpenDialogSuppUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usersList;
    // End of variables declaration//GEN-END:variables
}
